//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSP.POS.APICrystalReport.Models.Reportes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Prueba_Gestor_ServiciosEntities5 : DbContext
    {
        public Prueba_Gestor_ServiciosEntities5()
            : base("name=Prueba_Gestor_ServiciosEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GenerarReporteDeInformePorConsecutivo_Result> GenerarReporteDeInformePorConsecutivo(string consecutivo, string eSQUEMA)
        {
            var consecutivoParameter = consecutivo != null ?
                new ObjectParameter("consecutivo", consecutivo) :
                new ObjectParameter("consecutivo", typeof(string));
    
            var eSQUEMAParameter = eSQUEMA != null ?
                new ObjectParameter("ESQUEMA", eSQUEMA) :
                new ObjectParameter("ESQUEMA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerarReporteDeInformePorConsecutivo_Result>("GenerarReporteDeInformePorConsecutivo", consecutivoParameter, eSQUEMAParameter);
        }
    }
}
